namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 2
      replication: false
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      replicas: 4
      replication: false
  clusterSelector:
    matchLabels:
      env: prod
